import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../supabaseClient'
import { useAuth } from '../contexts/AuthContext'
import PageHeader from '../components/PageHeader'
import PageCard from '../components/PageCard'

const MAX_HEALTHY_WEEKLY_HOURS = 30
const formatDate = new Intl.DateTimeFormat('tr-TR', { day: 'numeric', month: 'long', year: 'numeric' })

export default function Dashboard() {
  const { profile } = useAuth(); const [stats, setStats] = useState({ teachers: 0, courses: 0, branches: 0, constraints: 0 }); const [assignments, setAssignments] = useState([]); const [courses, setCourses] = useState([]); const [teachers, setTeachers] = useState([]); const [scheduleCount, setScheduleCount] = useState(0); const [loading, setLoading] = useState(true)
  useEffect(() => { fetchAll() }, [])
  async function fetchAll() { const results = await Promise.all([supabase.from('teachers').select('id, full_name'), supabase.from('courses').select('id, course_name'), supabase.from('branches').select('*', { count: 'exact', head: true }), supabase.from('teacher_constraints').select('*', { count: 'exact', head: true }), supabase.from('course_assignments').select('id, course_id, teacher_id, weekly_hours'), supabase.from('schedules').select('id', { count: 'exact', head: true })]); const teacherData = results[0].data || []; const courseData = results[1].data || []; setTeachers(teacherData); setCourses(courseData); setStats({ teachers: teacherData.length, courses: courseData.length, branches: results[2].count || 0, constraints: results[3].count || 0 }); setAssignments(results[4].data || []); setScheduleCount(results[5].count || 0); setLoading(false) }
  const totalRequiredHours = assignments.reduce((sum, a) => sum + (a.weekly_hours || 0), 0); const placed = Math.min(scheduleCount, totalRequiredHours); const remaining = Math.max(totalRequiredHours - scheduleCount, 0); const assignedCourseIds = new Set(assignments.map((a) => a.course_id)); const coursesWithoutTeacher = courses.filter((c) => !assignedCourseIds.has(c.id)); const hoursByTeacher = {}; assignments.forEach((a) => { hoursByTeacher[a.teacher_id] = (hoursByTeacher[a.teacher_id] || 0) + (a.weekly_hours || 0) }); const overloadedTeachers = teachers.filter((t) => (hoursByTeacher[t.id] || 0) > MAX_HEALTHY_WEEKLY_HOURS); const ready = remaining === 0 && coursesWithoutTeacher.length === 0 && overloadedTeachers.length === 0
  const checks = [{ label: 'Ders saatleri yerleşimi', value: remaining === 0 ? 'Tamamlandı' : `${remaining} saat eksik`, detail: `${placed} / ${totalRequiredHours || 0} saat`, to: '/schedule', good: remaining === 0 }, { label: 'Ders ve öğretmen eşleşmesi', value: coursesWithoutTeacher.length === 0 ? 'Tamamlandı' : `${coursesWithoutTeacher.length} ders eksik`, detail: coursesWithoutTeacher.length ? coursesWithoutTeacher.slice(0, 2).map((c) => c.course_name).join(', ') : 'Tüm derslerin sorumlusu var', to: '/assignments', good: coursesWithoutTeacher.length === 0 }, { label: 'Öğretmen haftalık yükü', value: overloadedTeachers.length === 0 ? 'Dengeli' : `${overloadedTeachers.length} kayıt incelenmeli`, detail: overloadedTeachers.length ? overloadedTeachers.slice(0, 2).map((t) => t.full_name).join(', ') : `Her öğretmen ${MAX_HEALTHY_WEEKLY_HOURS} saat altında`, to: '/assignments', good: overloadedTeachers.length === 0 }]

  return <div className="p-4 md:p-8 max-w-[1180px] mx-auto"><PageHeader title={`Merhaba, ${profile?.full_name?.split(' ')[0] || 'Müdür'}`} subtitle={`${formatDate.format(new Date())} · Haftalık programın yayınlama dosyası`} />
    <section className="border-y-2 border-[#202822] py-7 mb-8"><div className="flex flex-col md:flex-row md:items-end justify-between gap-6"><div><p className="font-mono text-[11px] uppercase tracking-[.14em] text-[#68726b] mb-3">Dosya durumu / 20 Eylül 2026</p><h2 className="text-3xl md:text-5xl font-semibold text-[#202822] max-w-xl leading-[1.03]">{ready ? 'Program yayınlanmaya hazır.' : 'Yayın öncesi kontroller sürüyor.'}</h2><p className="text-[#68726b] text-sm mt-4 max-w-xl leading-relaxed">Bu ekran, okulun haftalık programını öğretmenlerle paylaşmadan önce müdürün kontrol etmesi gereken kayıtları toplar.</p></div><div className="md:text-right"><p className="font-mono text-5xl font-semibold text-[#1f5c4b] tabular-nums">{loading ? '·' : `${totalRequiredHours ? Math.round((placed / totalRequiredHours) * 100) : 0}%`}</p><p className="font-mono text-[11px] uppercase tracking-wider text-[#68726b] mt-1">yerleşim tamamlandı</p></div></div></section>
    <div className="border-t border-[#cbcfc8]"><div className="grid grid-cols-[1.3fr_.7fr] gap-4 py-4 border-b border-[#cbcfc8] font-mono text-[10px] uppercase tracking-wider text-[#68726b]"><span>Kontrol</span><span>Kanıt</span></div>{checks.map((check, index) => <Link key={check.label} to={check.to} className="grid md:grid-cols-[56px_1.3fr_.7fr_100px] gap-3 items-center py-5 border-b border-[#cbcfc8] hover:bg-[#e1e5dc] transition-colors"><span className="font-mono text-sm text-[#68726b]">0{index + 1}</span><div><p className="font-semibold text-[#202822]">{check.label}</p><p className="text-xs text-[#68726b] mt-1">{check.detail}</p></div><p className="font-mono text-sm text-[#202822]">{check.value}</p><span className={'font-mono text-[10px] uppercase tracking-wider md:text-right ' + (check.good ? 'text-[#1f5c4b]' : 'text-[#a05d25]')}>{check.good ? 'uygun' : 'incele'}</span></Link>)}</div>
    <div className="grid md:grid-cols-2 gap-6 mt-8"><PageCard title="Okul özeti" description="Sistemde kayıtlı operasyon verisi"><dl className="divide-y divide-[#cbcfc8]">{[['Öğretmen', stats.teachers], ['Ders', stats.courses], ['Şube', stats.branches], ['Müsaitlik kısıtı', stats.constraints]].map(([label, value]) => <div key={label} className="flex justify-between py-3"><dt className="text-sm text-[#68726b]">{label}</dt><dd className="font-mono text-sm font-semibold text-[#202822]">{loading ? '·' : value}</dd></div>)}</dl></PageCard><PageCard title="Sonraki karar" description="Program henüz hazır değilse başla"><p className="text-sm text-[#202822] leading-relaxed">{ready ? 'Programı paylaşmadan önce son görünümü ve PDF çıktısını kontrol et.' : 'Önce program oluşturucuda boş saatleri tamamla. Ardından öğretmen yüklerini ve atamaları tekrar kontrol et.'}</p><Link to={ready ? '/schedule' : '/schedule'} className="inline-block mt-5 font-mono text-xs uppercase tracking-wider text-[#1f5c4b] border-b border-[#1f5c4b] pb-1">Program dosyasını aç →</Link></PageCard></div>
    <footer className="mt-12 pt-4 border-t border-[#cbcfc8] flex flex-wrap gap-x-5 gap-y-2 text-xs text-[#68726b]"><span>EduShift · Okul operasyon merkezi</span><a href="/terms" className="underline underline-offset-2">Şartlar</a><a href="/privacy" className="underline underline-offset-2">Gizlilik</a></footer>
  </div>
}
